server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:3306/potgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true